<style>
	#forgot {
		
		heigth : 200 px;
		width : 400px;
		display : block;
		border : 2px solid;
		margin: 0px auto;
		padding: 5px;
	}
	
	form dl dt {
			margin : 0 0 0 20px;
			float:  left;
			clear: left;
			width: 150px;
			padding:  0 10px 0 0;
			height:  24px;
			line-height: 24px;
		}
	
	.error {
		color: red;
	}
</style>

<div id="forgot">
	<h2>forgot your password ?</h2>
	<?php 
	echo $this->form ;
	
	?>
	<p><span class="error"><?php echo $this->mail;?></span></p>
	<p><span class="error"><?php echo $this->error;?></span></p>
	
	
</div>
