<style>
	#login {
		
		heigth : 200 px;
		width : 400px;
		display : block;
		border : 2px solid;
		margin: 0px auto;
		padding: 5px;
	}
	
	form dl dt {
			margin : 0 0 0 20px;
			float:  left;
			clear: left;
			width: 150px;
			padding:  0 10px 0 0;
			height:  24px;
			line-height: 24px;
		}
	
	.error {
		color: red;
	}
</style>

<div id="login">
	<h2>Login</h2>
	<?php 
	echo $this->form ;
	
	?>
	<p><span class="error"><?php echo $this->error;?></span></p>
	
	<a href="<?php echo $this->url(array('controller'=>'index', 
		            'action'=>'forgot'));?>" transition-link="" transition-name="slide">forgot your password</a>
	<a href="<?php echo $this->url(array('controller'=>'index', 
	            'action'=>'register'));?>" transition-link="" transition-name="slide">register</a>            
		            
</div>
