<style>

	
	.error {
		color: red;
	}
	
	form dl dt {
			margin : 0 0 0 20px;
			float:  left;
			clear: left;
			width: 150px;
			padding:  0 10px 0 0;
			height:  24px;
			line-height: 24px;
		}
</style>
<h2>Edit a user</h2>
<?php 
echo $this->form ;
?>
<p>
	User is in following group(s) :
	<?php 
		    	foreach($this->user->getGroup() as $group) :
		    		echo $group->getName() . ' ';
		    	endforeach;
		    	?> 
</p>
<p><span class="error"><?php echo $this->error;?></span></p>