<h2>Edit Group</h2>
<?php echo $this->form ; ?>

<table>
		<tr>
		    <th>Users</th>
		   	<th>Actions</th>
		</tr>
		<?php foreach($this->users as $user) : ?>
		<tr>
		    <td><?php echo $this->escape($user->getEmail());?></td>
		    <td>
		    <a href="<?php echo $this->url(array('controller'=>'user', 
		            'action'=>'deleteuserfromgroup', 'userid'=>$user->getId()));?>">Delete</a>
		            
		    
		</tr>
		<?php endforeach; 
		
		?>
		</table>