<style>
dd , dt {
	float : left ;
}

dl {
	margin:  0 0 0 20px ; 
}
</style>
      <h2>view users</h2>
      
      <?php echo $this->form ; ?>
     
      <table>
		<tr>
		    <th>First name </th>
		    <th>Last name</th>
		    <th>Email</th>
		    <th>groups</th>
		    <th>actions</th>
		</tr>
		<?php foreach($this->paginator as $user) : ?>
		<tr>
		    <td><?php echo $this->escape($user->getFirstName());?></td>
		    
		    <td><?php echo $this->escape($user->getLastName());?></td>
		    <td><?php echo $this->escape($user->getEmail());?></td>
		    <td>
		    	<?php 
		    	foreach($user->getGroup() as $group) :
		    		echo $group->getName() . ' ';
		    	endforeach;
		    	?>
		    </td>
		    <td>
		        <a href="<?php echo $this->url(array('controller'=>'user', 
            		'action'=>'edit', 'id'=>$user->getId()));?>">Edit</a>
		        <a href="<?php echo $this->url(array('controller'=>'user', 
		            'action'=>'delete', 'id'=>$user->getId()));?>">Delete</a>
		    </td>
		</tr>
		<?php endforeach; ?>
		</table>

	<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'paging.phtml',$this->search); ?>
    <a href="<?php echo $this->url(array('controller'=>'user', 
		            'action'=>'add'));?>" transition-link="" transition-name="slide">add user </a>
	
